### ISSUE TITLE
Rename tab not intuitive (UI improvement)

### ISSUE THREAD

**Issue by chaosarium** [MarkChenYutian/C0VM-ts#16]
I couldn't figure out how to rename a tab without searching through the documentation. `alt` + left click is probably not something people think of.

Maybe double click or right click menu with rename option would be more intuitive.

**Comment by MarkChenYutian** [comment]
This behavior is defined in here, specifically:

https://github.com/MarkChenYutian/C0VM-ts/blob/8e45bd38c1703cbe6e027cdb69c851129ef7ec84/src/components/c0-editor-group.tsx#L57-L62
