### ISSUE TITLE
Drag and drop not working

### ISSUE THREAD

**Issue by chaosarium** [MarkChenYutian/C0VM-ts#17]
Tested on Mac using Safari, Chrome, and Firefox

![Capture d’écran 2022-11-20 at 12 22 32](https://user-images.githubusercontent.com/38693485/202916453-27ed73a4-d985-4c1d-955b-d0c4ebdf7a16.gif)

**Comment by chaosarium** [comment]
Also, does it support drag and drop folder to open all c0 files in the folder?

**Comment by MarkChenYutian** [comment]
No, currently we only support drag & drop to load one single file at a time.

**Comment by MarkChenYutian** [comment]
Some thought about this bug: it is possible that the D&D tab list in C0EditorGroup has intercepted the drop event from passing to C0Editor component. Will check & fix this in winter break.

**Comment by MarkChenYutian** [comment]
Consider changing current draggable tab into this: https://reactjsexample.com/draggable-atom-like-tabs-for-react/

**Comment by MarkChenYutian** [comment]
Unfortunately, the PR #23 is not able to fix this problem as the attempt to separate `DraggableTabs` and `C0Editor` components cause the editor to crash constantly.

**Comment by MarkChenYutian** [comment]
It's very hard to fix ... For now I've deleted the `use Drag & Drop to import file` prompt in the editor...

**Comment by MarkChenYutian** [comment]
The problem lays inside of `DraggableTabs` and is very hard to fix.
