### ISSUE TITLE
Running factorial gives error [Bug Report]

### ISSUE THREAD

**Issue by amandaLi7** [MarkChenYutian/C0VM-ts#3]
I tried importing fact.bc0 into the editor. It gives me a getBigUint64 error. I'm working on a MacBook Pro, 2020 M1 running MacOS BigSur, through Safari. 

1. Go to BC0 editor.
2. Load Manually fact.bc0, can be found/produced from C0VM assignment
3. Click Run. See error.

**Expected behavior**
I believe that it should work, and start running the byte code.

[Screen Recording 2022-08-22 at 6.17.02 PM.mov.zip](https://github.com/MarkChenYutian/C0VM-ts/files/9398197/Screen.Recording.2022-08-22.at.6.17.02.PM.mov.zip)

**Comment by amandaLi7** [comment]
```
C0 C0 FF EE       # magic number
00 17             # version 11, arch = 1 (64 bits)

00 00             # int pool count
# int pool

00 18             # string pool total size
# string pool
20 69 73 20 74 68 65 20 66 61 63 74 6F 72 69 61 6C 20 6F 66 20 31 35 00  # " is the factorial of 15"

00 02             # function count
# function_pool

#<main>
00                # number of arguments = 0
00                # number of local variables = 0
00 13             # code length = 19 bytes
10 0F    # bipush 15          # 15
B8 00 01 # invokestatic 1     # factorial(15)
B7 00 00 # invokenative 0     # printint(factorial(15))
57       # pop                # (ignore result)
14 00 00 # aldc 0             # s[0] = " is the factorial of 15"
B7 00 01 # invokenative 1     # println(" is the factorial of 15")
57       # pop                # (ignore result)
10 00    # bipush 0           # 0
B0       # return             # 


#<factorial>
01                # number of arguments = 1
01                # number of local variables = 1
00 1B             # code length = 27 bytes
15 00    # vload 0            # n
10 00    # bipush 0           # 0
9F 00 06 # if_cmpeq +6        # if (n == 0) goto <00:cond_true>
A7 00 08 # goto +8            # goto <01:cond_false>
# <00:cond_true>
10 01    # bipush 1           # 1
A7 00 0E # goto +14           # goto <02:cond_end>
# <01:cond_false>
15 00    # vload 0            # n
15 00    # vload 0            # n
10 01    # bipush 1           # 1
64       # isub               # (n - 1)
B8 00 01 # invokestatic 1     # factorial((n - 1))
68       # imul               # (n * factorial((n - 1)))
# <02:cond_end>
B0       # return             # 

00 02             # native count
# native pool
00 01 00 09       # printint
00 01 00 0A       # println


```

**Comment by MarkChenYutian** [comment]
Received! I'll dig into it tonight.

**Comment by MarkChenYutian** [comment]
@amandaLi7 Hi, which browser are you using when this error occurs?

I've tried to run this code on Firefox and Microsoft Edge and the error didn't pop out.

![image](https://user-images.githubusercontent.com/47029019/186037013-f62b1068-7d84-4f03-8adc-edd287e65d46.png)

**Comment by MarkChenYutian** [comment]
This seems like a browser-dependent problem. I've tried to run this byte code on Firefox and Chrome and the error didn't pop out.

**Comment by amandaLi7** [comment]
Yes, Chrome seems to work. I guess warn off testers from using Safari for now haha. 
Also, very cool project, will give more feedback now that I can use it.

**Comment by MarkChenYutian** [comment]
That's weird... I've tried this in Safari on my MacBook, but failed to reproduce this problem.

<img width="1440" alt="Screen Shot 2022-08-22 at 19 32 02" src="https://user-images.githubusercontent.com/47029019/186037719-c6210e68-b98b-44f8-b155-40977fcf5671.png">

Could you open the console after this error occurs and take a screen shot? The call stack will be dumped in console in debug mode.

**Comment by MarkChenYutian** [comment]
btw, glad to hear that you enjoy this project 😄

**Comment by amandaLi7** [comment]
Hm, for some reason, it's empty for me. (I'm assuming you mean Console in Web Inspector).
<img width="1438" alt="Screen Shot 2022-08-22 at 6 46 21 PM" src="https://user-images.githubusercontent.com/40663739/186038861-a0db1913-16b6-41a2-9050-7498e6870da0.png">

And just to double check, the website URL I'm using is https://markchenyutian.github.io/C0VM-ts/build/

**Comment by MarkChenYutian** [comment]
Yes, I mean the console in inspector and the URL is correct. Sadly, this indicates that the error was caught silently.

However, after inspecting the source code & minimized JS, I suspect the error comes from

```typescript
export function isNullPtr(ptr: C0Pointer): boolean {
    return ptr.getBigUint64(0) === BigInt(0);
}
```

in `src/utility/pointer_utility.ts`.

I've add a `try ... catch ...` on it to log the `e` when error occurs and update the website now, could you re-run the program and see if anything got logged in the console? (note: the version number on left corner should now be `v0.2.6-alpha`)

**Comment by amandaLi7** [comment]
Great. Here's my console output. I've created a video since it gets nested. Feel free to pause whenever to get the info you want.
[Screen Recording 2022-08-22 at 10.11.08 PM.mov.zip](https://github.com/MarkChenYutian/C0VM-ts/files/9399050/Screen.Recording.2022-08-22.at.10.11.08.PM.mov.zip)

**Comment by MarkChenYutian** [comment]
Thanks for the screen recording.

Turns out this is a problem with Safari's support to `bigint` (a.k.a. `long` in `C`). 

A similar complain is found in [This issue](https://github.com/timostamm/protobuf-ts/issues/24). I'll fix this problem by changing `getBigUint64(0)` to `getUint32(0) === 0 && getUint32(4) === 0`.

**Comment by MarkChenYutian** [comment]
Could you try again to run the program? Just to make sure the fix being applied do work.

**Comment by amandaLi7** [comment]
Yep, looks good now!
