### ISSUE TITLE
[Bug Report] Editor Tab Name not updated properly

### ISSUE THREAD

**Issue by MarkChenYutian** [MarkChenYutian/C0VM-ts#34]
**Describe the bug**
When importing the file, the editor tab name is not set to imported file's name.

**To Reproduce**
1. Import a C0 file into the editor using "Load File" button 
2. Notice that the editor tab name is still `Untitled_0.c0`
3. Switch to BC0 editor
4. Switch back to C0 editor, and the name is now rendered correctly

**Expected behavior**
The displayed editor tab name is updated correctly when the file is imported.

**Screenshots**
(N/A)

**Code being executed**
(N/A)

**Additional context**
I suspect this is related to the recent update of editor tab rename feature (PR #28 ).

**Comment by chaosarium** [comment]
Interesting. Seems to work fine on the [tab-rename-fix](https://github.com/MarkChenYutian/C0VM-ts/tree/tab-rename-fix) branch and on commit c7f9311f4d62b78212502d461839489c1f1df607. Could it have been an issue with 88e5e64a2887bd9b545c2c20dbdec32cf39d3272?

**Comment by MarkChenYutian** [comment]
I'm suspecting that the `react-18-autoresize-input` has broken something internally. Can you take a look into this package?

**Comment by chaosarium** [comment]
> I'm suspecting that the `react-18-autoresize-input` has broken something internally. Can you take a look into this package?

sure

**Comment by chaosarium** [comment]
Just logging investigation progress. 

Switching back to `react-autoresize-input` doesn't make the issue go away. 

It seems like that, after loading file, `EditableTab`'s `props.title` is updated but `state.title` is not.

**Comment by chaosarium** [comment]
@MarkChenYutian was there a change to how `set_tab_name` works? I don't know if changing `this.props.setTabName` to `this.set_tab_name` affected React's state update.

Anyhow, a fix is on the way. It checks if `EditableTab` should get updated and updates accordingly.
