### ISSUE TITLE
[Bug Report] Negation Mod does not work as expected

### ISSUE THREAD

**Issue by cekington** [MarkChenYutian/C0VM-ts#39]
**Describe the bug**
negation mod does not work 

**To Reproduce**
print -3 % 4

**Expected behavior**
-3

**Screenshots**
N/A

**Code being executed**
printint(-3 % 4);

**Additional context**
N/A

**Comment by MarkChenYutian** [comment]
After investigation, this problem is caused by a dust on the laptop screen, which turns "-3" into "3" on the debug console.

This issue is therefore closed and it is always recommended to keep the display clean 😄 .
