### ISSUE TITLE
Display Operand Stack [Feature]

### ISSUE THREAD

**Issue by amandaLi7** [MarkChenYutian/C0VM-ts#4]
**Description**
Opcode actions like bipush, add, sub, etc manipulate the operand stack. It would be cool to have a visual in <Graph> mode and/or <Table> mode to display this, in addition to the function call stack you already have.

<img width="1440" alt="Screen Shot 2022-08-22 at 6 36 38 PM" src="https://user-images.githubusercontent.com/40663739/186038292-7dea84f6-ed15-47e7-9096-d8b73ed9f1db.png">

So for example in the situation above, we would have `n` in the operand stack, and then after executing that line, `1` would be added.

**Comment by MarkChenYutian** [comment]
This is definitely something I would like to add!

Hopefully this will be added as a separate view of debug console in the near future (maybe called "Detailed"?).

**Comment by MarkChenYutian** [comment]
<img width="1318" alt="image" src="https://user-images.githubusercontent.com/47029019/202861129-3fa00979-1a8a-4ae5-bb0b-a670917cb870.png">

This feature is added, and we will be able to playtest this on the upcoming C0VM assignment!

*Note:* The "detail" debug view is available only when "Expose Bytecode" option is on in Settings > Advanced Settings. So we can disable it when students haven't learn about bytecode to avoid confusing students.
