### ISSUE TITLE
[Bug Report] Not Compatible with WeChat Browser

### ISSUE THREAD

**Issue by Hao-Kang** [MarkChenYutian/C0VM-ts#6]
**Describe the bug**
Application Crashed with WeChat Browser

**To Reproduce**
1. Go to [http://visualc0.tk/docs/](http://visualc0.tk/docs/) with WeChat Browser
2. See the Error

**Expected behavior**
C0VM-ts should expectedly work on a variety of browsers.

**Screenshots**
![image](https://user-images.githubusercontent.com/89672451/194403190-74d3a9c7-4811-4237-80fc-bc21bd9ab7e0.png)

**Additional context**
```
{
    "Version": "0.3.0",
    "ReactState": {
        "crashed": true,
        "dbgFullScreen": false,
        "settingMenuOn": false,
        "BC0SourceCode": "",
        "BC0BreakPoints": {},
        "TypedefRecord": {},
        "C0Editors": [
            {
                "title": "Untitled_0.c0",
                "key": 0,
                "content": ""
            }
        ],
        "ActiveEditor": 0,
        "C0BreakPoint": {},
        "PrintoutValue": "",
        "C0Running": false,
        "CompilerFlags": {
            "d": false
        }
    },
    "ReactContext": {
        "mode": "full-page",
        "std_out": true,
        "debug_console": true,
        "c0_only": true
    },
    "GlobalState": {
        "configuration": {
            "DEBUG": true,
            "DEBUG_DUMP_MEM": false,
            "DEBUG_DUMP_STEP": false,
            "MEM_POOL_SIZE": 51200
        }
    }
}
```

**Comment by MarkChenYutian** [comment]
This can't be solved simply since `StructuredClone` is a WebAPI function and it's hard to do polyfill on WeChat browser.

I'll add a special check for browser compatibility (i.e. detect WeChat browser) and popup some elegant error message that guides user to open page on REAL browser.

**Comment by MarkChenYutian** [comment]
Turns out the `structuredClone` is a very new standard of WebAPI and there are potentially many browsers that does not support it, I'm considering to apply some polyfilled version of `structuredClone` in this project.

https://developer.mozilla.org/en-US/docs/Web/API/structuredClone

<img width="620" alt="Screen Shot 2022-10-12 at 14 48 35" src="https://user-images.githubusercontent.com/47029019/195423898-713167a9-6220-4471-9ca8-44a23bfe7d2a.png">

**Comment by MarkChenYutian** [comment]
This issue is resolved by removing all `StructuredClone` WebAPI calls in project. Now the web app can function properly on WeChat browser.
