### ISSUE TITLE
[Bug Report] Step Does Not Validate Modified C0 File

### ISSUE THREAD

**Issue by Hao-Kang** [MarkChenYutian/C0VM-ts#7]
**Describe the bug**
After `Compile`, if we modify the C0 File (even with an invalid one), `Step` would not raise an error. `Step` behaves as if the C0 File hasn't been modified. This is unexpected.

**To Reproduce**

https://user-images.githubusercontent.com/89672451/194408063-303949e2-9f71-4a67-81a2-392577a12033.mp4

**Expected behavior**
Ideally, C0VM-ts should detect changes in C0 File before proceeding to `Step`.

**Code being executed**
The old C0 File:
```
int main() {
    int b = 1;
    int c = b + 1;
    return c;
}
```
The modified C0 File:
```
int main() {
    int b = 0;
    int main() {
        return b + 1;
    }
    return b;
}
```

**Comment by MarkChenYutian** [comment]
Now, if the user edited C0 source code and hit the `Step` / `Run` button again, a "Recompile Required" Warning will pop out from and force user to recompile before executing the program.
